name: Infrastructure
description: Verify or deploy infrastructure to Azure

inputs:
  deploy:
    description: 'Whether to deploy the infrastructure'
    required: true
    default: "false"
  tenant_id:
    description: 'The tenant id of the federated user' 
    required: true
  subscription_id:
    description: 'The subscription to deploy to'
    required: true
  parameter_file:
    description: 'The parameter file to use'
    required: true
  environment:
    description: 'The environment to deploy to'
    required: true
    default: 'dev'
  template_file:
    description: 'The template file to use'
    required: true
    default: 'main.bicep'
  client_id:
    description: 'The client id of the federated user'
    required: true
  deployment_name:
    description: 'The name of the deployment'
    required: true
    default: 'infrastructure'
  resource_group:
    description: 'The name of the resource group'
    required: true


outputs:
  function_app_name:
    description: 'The name of the function app'
    value: ${{ steps.infra.outputs.functionAppName }}
  static_web_app_name:
    description: 'The name of the static web app'
    value: ${{ steps.infra.outputs.staticWebAppName }}

runs:
  using: composite

  steps:
    - uses: actions/checkout@v4
      
    - name: Azure CLI Login
      uses: azure/login@v2
      with:
        client-id: ${{ inputs.client_id }}
        tenant-id: ${{ inputs.tenant_id }}
        subscription-id: ${{ inputs.subscription_id }}
            
    - name: Verify or deploy infrastructure
      uses: azure/arm-deploy@v2
      id: infra
      with:
        subscriptionId: ${{ inputs.subscriptionId }}
        resourceGroupName: ${{ inputs.resource_group }}
        template: ${{ inputs.template_file }}
        parameters: ${{ inputs.parameter_file }}
        failOnStdErr: true
        scope: "resourcegroup"
        deploymentMode: ${{ inputs.deploy == 'true' && 'Incremental' || 'Validate' }}
        additionalArguments: "--name ${{ inputs.deployment_name }}"
